Repository gnuradio/gnuradio, pull requests merged in 2018-03, with the labels that each got.

#1653 digital: d_setlock mutex around modification of symbol LUT
  gr-digital/lib/chunks_to_symbols_XX_impl.cc.t
Labels: threading

#1657 qtgui: Fix some -Wreorder warnings
  gr-qtgui/lib/freq_sink_c_impl.cc
  gr-qtgui/lib/sink_c_impl.cc
  gr-qtgui/lib/sink_f_impl.cc
  gr-qtgui/lib/time_sink_c_impl.cc
  gr-qtgui/lib/waterfall_sink_c_impl.cc
Labels: Cleanup, QTGUI

#1662 add missing includes to headers + reorder qtgui includes
  gr-blocks/lib/stream_pdu_base.h
  gr-fec/include/gnuradio/fec/polar_common.h
  gr-qtgui/lib/SpectrumGUIClass.cc
  gr-qtgui/lib/ber_sink_b_impl.cc
  gr-qtgui/lib/ber_sink_b_impl.h
  gr-qtgui/lib/const_sink_c_impl.cc
  gr-qtgui/lib/const_sink_c_impl.h
  gr-qtgui/lib/constellationdisplayform.cc
  gr-qtgui/lib/displayform.cc
  gr-qtgui/lib/edit_box_msg_impl.cc
  gr-qtgui/lib/edit_box_msg_impl.h
  gr-qtgui/lib/freq_sink_c_impl.cc
  gr-qtgui/lib/freq_sink_c_impl.h
  gr-qtgui/lib/freq_sink_f_impl.cc
  gr-qtgui/lib/freq_sink_f_impl.h
  gr-qtgui/lib/freqcontrolpanel.cc
  gr-qtgui/lib/freqdisplayform.cc
  gr-qtgui/lib/histogram_sink_f_impl.cc
  gr-qtgui/lib/histogram_sink_f_impl.h
  gr-qtgui/lib/histogramdisplayform.cc
  gr-qtgui/lib/number_sink_impl.cc
  gr-qtgui/lib/number_sink_impl.h
  gr-qtgui/lib/numberdisplayform.cc
  gr-qtgui/lib/plot_raster.cc
  gr-qtgui/lib/plot_waterfall.cc
  gr-qtgui/lib/qtgui_util.cc
  gr-qtgui/lib/sink_c_impl.cc
  gr-qtgui/lib/sink_c_impl.h
  gr-qtgui/lib/sink_f_impl.cc
  gr-qtgui/lib/sink_f_impl.h
  gr-qtgui/lib/spectrumdisplayform.cc
  gr-qtgui/lib/timeRasterGlobalData.cc
  gr-qtgui/lib/time_raster_sink_b_impl.cc
  gr-qtgui/lib/time_raster_sink_b_impl.h
  gr-qtgui/lib/time_raster_sink_f_impl.cc
  gr-qtgui/lib/time_raster_sink_f_impl.h
  gr-qtgui/lib/time_sink_c_impl.cc
  gr-qtgui/lib/time_sink_c_impl.h
  gr-qtgui/lib/time_sink_f_impl.cc
  gr-qtgui/lib/time_sink_f_impl.h
  gr-qtgui/lib/timedisplayform.cc
  gr-qtgui/lib/timerasterdisplayform.cc
  gr-qtgui/lib/vector_sink_f_impl.cc
  gr-qtgui/lib/vector_sink_f_impl.h
  gr-qtgui/lib/vectordisplayform.cc
  gr-qtgui/lib/waterfallGlobalData.cc
  gr-qtgui/lib/waterfall_sink_c_impl.cc
  gr-qtgui/lib/waterfall_sink_c_impl.h
  gr-qtgui/lib/waterfall_sink_f_impl.cc
  gr-qtgui/lib/waterfall_sink_f_impl.h
  gr-qtgui/lib/waterfalldisplayform.cc
Labels: Cleanup

#1673 runtime: make py_io_signature iterable, hashable
  gnuradio-runtime/python/gnuradio/gr/gateway.py
Labels: Bug, GRC, Python

#1695 Fix typos in PFB docs.
  gr-filter/grc/filter_pfb_channelizer.xml
  gr-filter/include/gnuradio/filter/pfb_arb_resampler.h
  gr-filter/include/gnuradio/filter/pfb_arb_resampler_fff.h
  gr-filter/include/gnuradio/filter/pfb_channelizer_ccf.h
  gr-filter/include/gnuradio/filter/pfb_decimator_ccf.h
  gr-filter/include/gnuradio/filter/pfb_interpolator_ccf.h
  gr-filter/include/gnuradio/filter/polyphase_filterbank.h
Labels: Documentation

#1697 fix broken gr-uhd command tags
  gr-uhd/lib/usrp_block_impl.cc
  gr-uhd/lib/usrp_block_impl.h
Labels: gr-uhd

#1698 [gr-fec] Define GSL_LDFLAGS in MSVC build
  cmake/Modules/FindGSL.cmake
Labels: msvc

#1700 fft: fix FFTW wisdom file locking for fft_real_fwd and fft_real_rev
  gr-fft/lib/fft.cc
Labels: Bug

#1679 Fix #1678: Avoid creation of same blockname
  gr-utils/python/modtool/modtool_add.py
Labels: enhancement, modtool

#1703 Test: adds swig dirs to python tests to allow ctest to run on win builds
  gnuradio-runtime/python/gnuradio/gr/CMakeLists.txt
  gnuradio-runtime/python/pmt/CMakeLists.txt
  gr-analog/python/analog/CMakeLists.txt
  gr-atsc/python/atsc/CMakeLists.txt
  gr-audio/python/audio/CMakeLists.txt
  gr-blocks/python/blocks/CMakeLists.txt
  gr-channels/python/channels/CMakeLists.txt
  gr-comedi/python/comedi/CMakeLists.txt
  gr-digital/python/digital/CMakeLists.txt
  gr-dtv/python/dtv/CMakeLists.txt
  gr-fcd/python/fcd/CMakeLists.txt
  gr-fec/python/fec/CMakeLists.txt
  gr-fft/python/fft/CMakeLists.txt
  gr-filter/python/filter/CMakeLists.txt
  gr-noaa/python/noaa/CMakeLists.txt
  gr-pager/python/pager/CMakeLists.txt
  gr-qtgui/python/qtgui/CMakeLists.txt
  gr-trellis/python/trellis/CMakeLists.txt
  gr-uhd/python/uhd/CMakeLists.txt
  gr-video-sdl/python/video_sdl/CMakeLists.txt
  gr-vocoder/python/vocoder/CMakeLists.txt
  gr-wavelet/python/wavelet/CMakeLists.txt
  gr-zeromq/python/zeromq/CMakeLists.txt
Labels: QA, msvc

#1670 runtime: remove gr::sys_pri
  gnuradio-runtime/include/gnuradio/CMakeLists.txt
  gnuradio-runtime/include/gnuradio/realtime_impl.h
  gnuradio-runtime/include/gnuradio/sys_pri.h
  gnuradio-runtime/lib/sys_pri.cc
Labels: Cruft

#1672 fix #1587: edit copyright in gr_modtool generated files
  gr-utils/python/modtool/gr-newmod/CMakeLists.txt
  gr-utils/python/modtool/gr-newmod/apps/CMakeLists.txt
  gr-utils/python/modtool/gr-newmod/cmake/Modules/GrMiscUtils.cmake
  gr-utils/python/modtool/gr-newmod/cmake/Modules/GrPlatform.cmake
  gr-utils/python/modtool/gr-newmod/cmake/Modules/GrPython.cmake
  gr-utils/python/modtool/gr-newmod/cmake/Modules/GrSwig.cmake
  gr-utils/python/modtool/gr-newmod/cmake/Modules/GrTest.cmake
  gr-utils/python/modtool/gr-newmod/docs/CMakeLists.txt
  gr-utils/python/modtool/gr-newmod/docs/doxygen/CMakeLists.txt
  gr-utils/python/modtool/gr-newmod/docs/doxygen/doxyxml/__init__.py
  gr-utils/python/modtool/gr-newmod/docs/doxygen/doxyxml/base.py
  gr-utils/python/modtool/gr-newmod/docs/doxygen/doxyxml/doxyindex.py
  gr-utils/python/modtool/gr-newmod/docs/doxygen/doxyxml/text.py
  gr-utils/python/modtool/gr-newmod/docs/doxygen/swig_doc.py
  gr-utils/python/modtool/gr-newmod/grc/CMakeLists.txt
  gr-utils/python/modtool/gr-newmod/include/howto/CMakeLists.txt
  gr-utils/python/modtool/gr-newmod/include/howto/api.h
  gr-utils/python/modtool/gr-newmod/lib/CMakeLists.txt
  gr-utils/python/modtool/gr-newmod/lib/qa_howto.cc
  gr-utils/python/modtool/gr-newmod/lib/qa_howto.h
  gr-utils/python/modtool/gr-newmod/lib/test_howto.cc
  gr-utils/python/modtool/gr-newmod/python/CMakeLists.txt
  gr-utils/python/modtool/gr-newmod/python/build_utils.py
  gr-utils/python/modtool/gr-newmod/python/build_utils_codes.py
  gr-utils/python/modtool/gr-newmod/swig/CMakeLists.txt
  gr-utils/python/modtool/modtool_add.py
  gr-utils/python/modtool/scm.py
Labels: Python, enhancement, modtool

#1690 Better documentation explaining what QPSK is doing.
  gr-digital/include/gnuradio/digital/constellation.h
Labels: Documentation

#1693 docs: Fix typo in gr-fec
  gr-fec/docs/fec.dox
Labels: Documentation

#1699 grc: Fixed pasting blocks from clipboard
  grc/gui/canvas/flowgraph.py
Labels: GRC
