Repository gnuradio/gnuradio, pull requests merged in 2018-06, with the labels that each got.

#1810 Ensure that stdint is found in float_array_to_int
  gr-blocks/lib/float_array_to_int.cc
Labels: Bug, C++11, master

#1830 digital: qa_packet_format fix conditionals to wait for messages
  gr-digital/python/digital/qa_packet_format.py
Labels: Backport-3.7, Bug, QA

#1838 ATSC Boost UTF
  gr-atsc/lib/CMakeLists.txt
  gr-atsc/lib/qa_atsci.cc
  gr-atsc/lib/qa_atsci.h
  gr-atsc/lib/qa_atsci_basic_trellis_encoder.cc
  gr-atsc/lib/qa_atsci_basic_trellis_encoder.h
  gr-atsc/lib/qa_atsci_data_interleaver.cc
  gr-atsc/lib/qa_atsci_data_interleaver.h
  gr-atsc/lib/qa_atsci_equalizer_nop.cc
  gr-atsc/lib/qa_atsci_equalizer_nop.h
  gr-atsc/lib/qa_atsci_fake_single_viterbi.cc
  gr-atsc/lib/qa_atsci_fake_single_viterbi.h
  gr-atsc/lib/qa_atsci_fs_correlator.cc
  gr-atsc/lib/qa_atsci_fs_correlator.h
  gr-atsc/lib/qa_atsci_randomizer.cc
  gr-atsc/lib/qa_atsci_randomizer.h
  gr-atsc/lib/qa_atsci_reed_solomon.cc
  gr-atsc/lib/qa_atsci_reed_solomon.h
  gr-atsc/lib/qa_atsci_single_viterbi.cc
  gr-atsc/lib/qa_atsci_single_viterbi.h
  gr-atsc/lib/qa_atsci_sliding_correlator.cc
  gr-atsc/lib/qa_atsci_sliding_correlator.h
  gr-atsc/lib/qa_atsci_trellis_encoder.cc
  gr-atsc/lib/qa_atsci_trellis_encoder.h
  gr-atsc/lib/qa_atsci_viterbi_decoder.cc
  gr-atsc/lib/qa_atsci_viterbi_decoder.h
  gr-atsc/lib/qa_convolutional_interleaver.cc
  gr-atsc/lib/qa_convolutional_interleaver.h
  gr-atsc/lib/qa_interleaver_fifo.cc
  gr-atsc/lib/qa_interleaver_fifo.h
  gr-atsc/lib/test_atsci.cc
Labels: Cruft

#1826 tests: added option to pass verbosity parameter (and fixed some styling)
  gnuradio-runtime/python/gnuradio/gr_unittest.py
Labels: QA, enhancement

#1745 grc: Added copyright holder to Options block
  grc/blocks/options.xml
  grc/core/generator/Generator.py
  grc/core/generator/flow_graph.tmpl
Labels: GRC, enhancement

#1744 grc: set parent for file override confirmation dialog
  grc/gui/FileDialogs.py
Labels: Bug, GRC

#1846 Documented cppunit dependency removal
  CHANGELOG.md
  docs/doxygen/other/build_guide.dox.in
Labels: Documentation

#1756 Added template for message sink port for set_symbol_table in chunks_to_symbols
  gr-digital/grc/digital_chunks_to_symbols.xml
Labels: digital, enhancement

#1773 swig block.i: add void set_output_multiple(int multiple)
  gnuradio-runtime/swig/block.i
Labels: Bug, Runtime

#1747 fix incorrect strings passed to the log console appender
  gnuradio-runtime/lib/logger.cc
  gnuradio-runtime/lib/tpb_thread_body.cc
  gr-fec/lib/generic_decoder.cc
  gr-fec/lib/generic_encoder.cc
Labels: Backport-3.7, Bug, logging
