Repository gnuradio/gnuradio, pull requests merged in 2021-04, with the labels that each got.

#4467 gr_filter_design: conditionally enable save
  gr-filter/python/filter/design/filter_design.py
  gr-filter/python/filter/gui/GrFilterPlotWidget.py
Labels: Backport-3.8, Backport-3.9

#4429 gr-pdu: add time blocks and examples
  gr-pdu/examples/CMakeLists.txt
  gr-pdu/examples/pdu_tools_demo.grc
  gr-pdu/grc/pdu.tree.yml
  gr-pdu/grc/pdu_add_system_time.block.yml
  gr-pdu/grc/pdu_pdu_split.block.yml
  gr-pdu/grc/pdu_time_delta.block.yml
  gr-pdu/include/gnuradio/pdu/CMakeLists.txt
  gr-pdu/include/gnuradio/pdu/add_system_time.h
  gr-pdu/include/gnuradio/pdu/time_delta.h
  gr-pdu/lib/CMakeLists.txt
  gr-pdu/lib/add_system_time_impl.cc
  gr-pdu/lib/add_system_time_impl.h
  gr-pdu/lib/pdu_split_impl.cc
  gr-pdu/lib/pdu_split_impl.h
  gr-pdu/lib/time_delta_impl.cc
  gr-pdu/lib/time_delta_impl.h
  gr-pdu/python/pdu/bindings/CMakeLists.txt
  gr-pdu/python/pdu/bindings/add_system_time_python.cc
  gr-pdu/python/pdu/bindings/docstrings/add_system_time_pydoc_template.h
  gr-pdu/python/pdu/bindings/docstrings/time_delta_pydoc_template.h
  gr-pdu/python/pdu/bindings/python_bindings.cc
  gr-pdu/python/pdu/bindings/time_delta_python.cc
  gr-pdu/python/pdu/qa_add_system_time.py
  gr-pdu/python/pdu/qa_pdu_split.py
  gr-pdu/python/pdu/qa_time_delta.py
Labels: pdu

#4473 gr-uhd: fix command tuning (backport to maint-3.9)
  gr-uhd/lib/usrp_block_impl.cc
  gr-uhd/lib/usrp_block_impl.h
  gr-uhd/lib/usrp_sink_impl.h
  gr-uhd/lib/usrp_source_impl.h
Labels: Bug Fix, gr-uhd

#4334 gui : fix block can move outside top and left boundary
  grc/gui/canvas/flowgraph.py
Labels: Backport-3.8, Backport-3.9, Bug Fix, GRC

#4461 runtime: remove pybind for internal things
  gnuradio-runtime/python/gnuradio/gr/bindings/buffer_python.cc
Labels: Backport-3.9

#4483 grc: Check connection types, whether they match
  grc/core/Connection.py
Labels: Backport-3.8, Backport-3.9

#4516 grc: match data type aliases as well as types
  grc/core/Connection.py
  grc/core/Constants.py
Labels: Bug Fix, GRC, ported-to-3.8, ported-to-3.9

#4415 uhd: Add option to sync timestamp to PC Clock or GPS time on next 1PPS
  gr-uhd/grc/gen_uhd_usrp_blocks.py
Labels: Backport-3.9

#4529 revise README.md Prebuilt Binaries
  README.md
Labels: Documentation

#4522 grc: update id blackist with imports
  grc/core/FlowGraph.py
  grc/core/params/dtypes.py
  grc/core/params/param.py
Labels: Backport-3.8, Backport-3.9

#4476 cmake: Fix codec2 and MPIR find modules for Windows (conda).
  cmake/Modules/FindCodec2.cmake
  cmake/Modules/FindMPIR.cmake
Labels: Backport-3.9, CMake, Windows

#4477 cmake: Move swath of add_definitions to gnuradio-runtime target.
  CMakeLists.txt
  gnuradio-runtime/lib/CMakeLists.txt
Labels: Backport-3.9, CMake

#4537 blocks: Add msg port to set rotator's phase inc (backport to maint-3.9)
  gr-blocks/grc/blocks_rotator_cc.block.yml
  gr-blocks/include/gnuradio/blocks/rotator_cc.h
  gr-blocks/lib/rotator_cc_impl.cc
  gr-blocks/lib/rotator_cc_impl.h
  gr-blocks/python/blocks/bindings/rotator_cc_python.cc
  gr-blocks/python/blocks/qa_rotator_cc.py
Labels: ABI

#4530 Fix rational resampler yml
  gr-filter/grc/filter_rational_resampler_xxx.block.yml
Labels: Backport-3.8, Backport-3.9

#4520 grc: Fix option_attributes check on inherited type
  grc/core/blocks/_build.py
Labels: Backport-3.8, Backport-3.9

#4542 filter: filter_delay_fc documentation used to be unclear about delay
  gr-filter/include/gnuradio/filter/filter_delay_fc.h
  gr-filter/python/filter/bindings/filter_delay_fc_python.cc
Labels: Documentation, filter

#4509 filter: add cpp export for iir filter
  gr-filter/grc/filter_interp_fir_filter_xxx.block.yml
Labels: Backport-3.9, C++ Generation, filter
