Repository gnuradio/gnuradio, pull requests merged in 2024-11, with the labels that each got.

#7539 bindings: update mismatched hashes
  gr-fec/python/fec/bindings/viterbi_python.cc
  gr-uhd/python/uhd/bindings/rfnoc_block_python.cc
  gr-uhd/python/uhd/bindings/rfnoc_graph_python.cc
  gr-uhd/python/uhd/bindings/rfnoc_rx_streamer_python.cc
Labels: pybind11, Bug Fix

#7529 grc-qt: Fix errors in qt related tests
  grc/tests/test_qtbot.py
Labels: Bug Fix, Backport-3.10, GRC-Qt

#7531 README: update link to the GNU Radio 4 repo
  README.md
Labels: Documentation, Backport-3.10

#7540 CI: Check hashes
  .github/workflows/make-test.yml
Labels: CI, pybind11, Backport-3.10

#7553 runtime: fix OpenBSD doesn't have prctl()
  gnuradio-runtime/lib/thread/thread.cc
Labels: Runtime, Backport-3.10
